POST http://localhost:8080/sparql/query
Content-Type: application/json
Accept: application/json

{
  "query": "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX sante: <http://www.semanticweb.org/msi/ontologies/2023/9/sante_ont#>\n\nSELECT ?patient ?nom ?dateDeNaissance ?age ?adresse\nWHERE {\n  ?patient rdf:type sante:Patient.\n  ?patient sante:aPourNom ?nom.\n  ?patient sante:aPourDateDeNaissance ?dateDeNaissance.\n  ?patient sante:aPourAge ?age.\n  ?patient sante:apourAdresse ?adresse.\n}"
}
