/**
 * Generated by @openapi-codegen
 *
 * @version v0
 */
export type PatientResponseDTO = {
  patient?: string;
  nom?: string;
  dateDeNaissance?: string;
  /**
   * @format int32
   */
  age?: number;
  adresse?: string;
  aConsulté?: string;
  aMaladie?: string;
  dossierMédical?: string;
  aconsulté?: string;
  amaladie?: string;
};

export type EtablissementDeSanteDTO = {
  telephone?: string;
  /**
   * @format int32
   */
  capacite?: number;
  /**
   * @format double
   */
  tauxDeReduction?: number;
  adesServiceDurg?: string;
  apourNomEtab?: string;
};
