/**
 * Generated by @openapi-codegen
 *
 * @version v0
 */
export type VehicleStatsDTO = Record<string, any>;

export type VehicleResponseDTO = Record<string, any>;

export type SpecialiteStatsResponseDTO = {
  /**
   * @format int64
   */
  totalSpecialites?: number;
  /**
   * @format int32
   */
  minSpecialistes?: number;
  /**
   * @format int32
   */
  maxSpecialistes?: number;
};

export type SpecialiteResponseDTO = {
  specialite?: string;
  etablissementName?: string;
  aPourDesSpecialiste?: string;
};

export type PatientStatsDTO = {
  /**
   * @format int32
   */
  totalPatients?: number;
  /**
   * @format int32
   */
  minAge?: number;
  /**
   * @format int32
   */
  maxAge?: number;
};

export type PatientResponseDTO = {
  patient?: string;
  nom?: string;
  dateDeNaissance?: string;
  /**
   * @format int32
   */
  age?: number;
  adresse?: string;
  aConsulté?: string;
  aMaladie?: string;
  dossierMédical?: string;
  aconsulté?: string;
  amaladie?: string;
};

export type EtablissementStatsDTO = {
  /**
   * @format int64
   */
  totalEtablissements?: number;
  /**
   * @format int32
   */
  maxCapacity?: number;
  /**
   * @format int32
   */
  minCapacity?: number;
};

export type EtablissementReductionStatsDTO = {
  /**
   * @format int64
   */
  totalEtablissements?: number;
  /**
   * @format double
   */
  maxReduction?: number;
  /**
   * @format double
   */
  minReduction?: number;
  /**
   * @format double
   */
  avgReduction?: number;
};

export type EtablissementDeSanteDTO = {
  aPourNomEtab?: string;
  aDesServiceDurg?: string;
  telephone?: string;
  /**
   * @format int32
   */
  capacite?: number;
  /**
   * @format double
   */
  tauxDeReduction?: number;
};
